import type { Metadata } from 'next';
import Link from 'next/link';
import { GlassCard } from '@/components/GlassCard';
import { TrendingUp, Users, BookOpen, Target, Check } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Services | TradeSignal',
  description: 'Explore our professional trading signals, mentorship programs, and comprehensive education courses.',
};

export default function ServicesPage() {
  const services = [
    {
      icon: TrendingUp,
      title: 'Forex Signals',
      description: 'Professional trading signals for major and minor currency pairs with real-time analysis.',
      features: [
        'Real-time signal delivery',
        'Entry, exit, and stop-loss levels',
        'Technical analysis breakdown',
        'Daily market analysis',
        'Mobile app notifications',
      ],
      color: 'from-accent/20 to-transparent',
    },
    {
      icon: Target,
      title: 'Synthetic Indices Signals',
      description: 'Specialized signals for synthetic indices trading with consistent opportunities.',
      features: [
        'Synthetic indices analysis',
        'High probability setups',
        'Consistent entry points',
        'Risk management guidelines',
        'Pattern recognition signals',
      ],
      color: 'from-blue-500/20 to-transparent',
    },
    {
      icon: Users,
      title: 'Mentorship Program',
      description: 'One-on-one guidance from experienced traders to accelerate your learning.',
      features: [
        '1-on-1 trading sessions',
        'Portfolio analysis',
        'Strategy development',
        'Psychology coaching',
        'Monthly reviews',
      ],
      color: 'from-purple-500/20 to-transparent',
    },
    {
      icon: BookOpen,
      title: 'Trading Education',
      description: 'Comprehensive courses from beginner fundamentals to advanced strategies.',
      features: [
        'Video tutorials',
        'Live webinars',
        'Trading journal templates',
        'Strategy guides',
        'Downloadable resources',
      ],
      color: 'from-green-500/20 to-transparent',
    },
  ];

  const whyChoose = [
    {
      title: 'Expert Analysis',
      description: 'Signals generated by professional traders with 8+ years of market experience.',
    },
    {
      title: 'Risk Management',
      description: 'Every signal includes risk management guidelines to protect your capital.',
    },
    {
      title: '24/7 Support',
      description: 'Dedicated support team available to help with any questions or technical issues.',
    },
    {
      title: 'Community Access',
      description: 'Join our exclusive trading community to share ideas and learn from others.',
    },
    {
      title: 'Flexible Plans',
      description: 'Choose from Basic, Pro, or Elite plans based on your trading needs.',
    },
    {
      title: 'No Guarantees, Pure Learning',
      description: 'We focus on education and quality signals, not unrealistic profit promises.',
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-background via-background to-background/80">
      {/* Hero Section */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="text-center space-y-6 mb-16">
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-balance">
            Professional Trading <span className="text-accent">Services</span>
          </h1>
          <p className="text-xl text-foreground/70 max-w-2xl mx-auto">
            Everything you need to become a successful trader - signals, education, and expert mentorship.
          </p>
        </div>
      </section>

      {/* Services Grid */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-16">
          {services.map((service, index) => {
            const Icon = service.icon;
            return (
              <div key={index}>
                <GlassCard hover className="h-full">
                  <div className="flex gap-4 mb-6">
                    <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-accent/20 flex items-center justify-center">
                      <Icon size={24} className="text-accent" />
                    </div>
                    <div>
                      <h3 className="text-2xl font-bold">{service.title}</h3>
                      <p className="text-sm text-foreground/60 mt-1">{service.description}</p>
                    </div>
                  </div>

                  <div className="space-y-3">
                    <p className="text-sm font-semibold text-foreground/70 uppercase tracking-wide">
                      Includes:
                    </p>
                    <ul className="space-y-2">
                      {service.features.map((feature, idx) => (
                        <li key={idx} className="flex items-start gap-3">
                          <Check size={18} className="text-accent flex-shrink-0 mt-0.5" />
                          <span className="text-foreground/70">{feature}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <Link
                    href="/pricing"
                    className="block mt-6 px-4 py-2 rounded-lg border border-accent/40 text-accent font-medium hover:bg-accent/10 text-center transition-colors"
                  >
                    View Pricing
                  </Link>
                </GlassCard>
              </div>
            );
          })}
        </div>
      </section>

      {/* Why Choose Section */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <h2 className="text-3xl font-bold text-center mb-12">Why TradeSignal Traders Succeed</h2>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {whyChoose.map((item, index) => (
            <GlassCard key={index} hover>
              <h3 className="text-lg font-bold mb-3">{item.title}</h3>
              <p className="text-foreground/70">{item.description}</p>
            </GlassCard>
          ))}
        </div>
      </section>

      {/* Comparison Table */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <h2 className="text-3xl font-bold text-center mb-12">How Our Services Compare</h2>

        <div className="overflow-x-auto">
          <GlassCard>
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border/40">
                  <th className="text-left py-3 px-4 font-semibold">Feature</th>
                  <th className="text-center py-3 px-4 font-semibold">Signals</th>
                  <th className="text-center py-3 px-4 font-semibold">Education</th>
                  <th className="text-center py-3 px-4 font-semibold">Mentorship</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-border/40">
                  <td className="py-3 px-4">Real-time Signals</td>
                  <td className="text-center"><Check size={18} className="text-accent inline" /></td>
                  <td className="text-center">-</td>
                  <td className="text-center"><Check size={18} className="text-accent inline" /></td>
                </tr>
                <tr className="border-b border-border/40">
                  <td className="py-3 px-4">Video Courses</td>
                  <td className="text-center">-</td>
                  <td className="text-center"><Check size={18} className="text-accent inline" /></td>
                  <td className="text-center"><Check size={18} className="text-accent inline" /></td>
                </tr>
                <tr className="border-b border-border/40">
                  <td className="py-3 px-4">1-on-1 Sessions</td>
                  <td className="text-center">-</td>
                  <td className="text-center">-</td>
                  <td className="text-center"><Check size={18} className="text-accent inline" /></td>
                </tr>
                <tr className="border-b border-border/40">
                  <td className="py-3 px-4">Market Analysis</td>
                  <td className="text-center"><Check size={18} className="text-accent inline" /></td>
                  <td className="text-center"><Check size={18} className="text-accent inline" /></td>
                  <td className="text-center"><Check size={18} className="text-accent inline" /></td>
                </tr>
                <tr>
                  <td className="py-3 px-4">24/7 Support</td>
                  <td className="text-center"><Check size={18} className="text-accent inline" /></td>
                  <td className="text-center"><Check size={18} className="text-accent inline" /></td>
                  <td className="text-center"><Check size={18} className="text-accent inline" /></td>
                </tr>
              </tbody>
            </table>
          </GlassCard>
        </div>
      </section>

      {/* CTA Section */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <GlassCard gradient className="text-center py-12">
          <h2 className="text-3xl font-bold mb-4">Ready to Get Started?</h2>
          <p className="text-foreground/70 text-lg mb-8">
            Choose the perfect plan for your trading journey.
          </p>
          <Link
            href="/pricing"
            className="inline-block px-8 py-3 rounded-lg bg-accent text-background font-semibold hover:bg-accent/90 transition-colors"
          >
            View Pricing Plans
          </Link>
        </GlassCard>
      </section>
    </div>
  );
}
